#!/bin/bash
# Echo Assistant - Copy & Paste Setup Commands

echo "🚀 Echo Assistant Setup - Copy each command below and run in terminal"
echo ""
echo "=========================================="
echo "STEP 1: Deploy Backend Function"
echo "=========================================="
echo "Copy and paste this:"
echo ""
echo "supabase functions deploy echo-assistant"
echo ""
echo "Wait for: ✓ Function deployed successfully"
echo ""
echo ""
echo "=========================================="
echo "STEP 2: Set API Key"
echo "=========================================="
echo "Replace YOUR-API-KEY with your actual key, then run:"
echo ""
echo "supabase secrets set LOVABLE_API_KEY='YOUR-API-KEY'"
echo ""
echo "Examples:"
echo "  supabase secrets set LOVABLE_API_KEY='sk-1234567890'"
echo ""
echo ""
echo "=========================================="
echo "STEP 3: Restart Dev Server"
echo "=========================================="
echo "Stop current server (Ctrl+C), then run:"
echo ""
echo "npm run dev"
echo ""
echo "Open browser to: http://localhost:5173/echo-assistant"
echo ""
echo ""
echo "=========================================="
echo "STEP 4: Verify Setup (Optional)"
echo "=========================================="
echo "Check function deployed:"
echo "  supabase functions list"
echo ""
echo "Check secrets set:"
echo "  supabase secrets list"
echo ""
echo "View function logs:"
echo "  supabase functions logs echo-assistant --tail"
echo ""
echo "=========================================="
echo "✅ Done! Your Echo Assistant should now work!"
echo "=========================================="
